service: montreal-swing-calendar-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - 'arn:aws:dynamodb:us-east-1:934939427723:table/ApplicationTable'

functions:
  signup:
    handler: functions/user.signup
    events:
      - http:
          path: /signup
          method: post
          cors: true
    environment:
      TableName: ApplicationTable
  login:
    handler: functions/user.login
    events:
      - http:
          path: /login
          method: post
          cors: true
    environment:
      TableName: ApplicationTable

resources:
  Resources:
    ApplicationTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ApplicationTable
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
